/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ISubmodelRepositoryInterfaceApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Deletes a Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns></returns>
        void DeleteSubmodelById (string submodelIdentifier);

        /// <summary>
        /// Deletes a Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteSubmodelByIdWithHttpInfo (string submodelIdentifier);
        /// <summary>
        /// Returns all Submodels
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="semanticId">The value of the semantic id reference (BASE64-URL-encoded) (optional)</param>
        /// <param name="idShort">The Submodel’s idShort (optional)</param>
        /// <returns>List&lt;Submodel&gt;</returns>
        List<Submodel> GetAllSubmodels (string semanticId = null, string idShort = null);

        /// <summary>
        /// Returns all Submodels
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="semanticId">The value of the semantic id reference (BASE64-URL-encoded) (optional)</param>
        /// <param name="idShort">The Submodel’s idShort (optional)</param>
        /// <returns>ApiResponse of List&lt;Submodel&gt;</returns>
        ApiResponse<List<Submodel>> GetAllSubmodelsWithHttpInfo (string semanticId = null, string idShort = null);
        /// <summary>
        /// Returns a specific Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Submodel</returns>
        Submodel GetSubmodelById (string submodelIdentifier);

        /// <summary>
        /// Returns a specific Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Submodel</returns>
        ApiResponse<Submodel> GetSubmodelByIdWithHttpInfo (string submodelIdentifier);
        /// <summary>
        /// Creates a new Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <returns>Submodel</returns>
        Submodel PostSubmodel (Submodel body);

        /// <summary>
        /// Creates a new Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <returns>ApiResponse of Submodel</returns>
        ApiResponse<Submodel> PostSubmodelWithHttpInfo (Submodel body);
        /// <summary>
        /// Creates a new or updates an existing Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Submodel</returns>
        Submodel PutSubmodelById (Submodel body, string submodelIdentifier);

        /// <summary>
        /// Creates a new or updates an existing Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Submodel</returns>
        ApiResponse<Submodel> PutSubmodelByIdWithHttpInfo (Submodel body, string submodelIdentifier);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Deletes a Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteSubmodelByIdAsync (string submodelIdentifier);

        /// <summary>
        /// Deletes a Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteSubmodelByIdAsyncWithHttpInfo (string submodelIdentifier);
        /// <summary>
        /// Returns all Submodels
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="semanticId">The value of the semantic id reference (BASE64-URL-encoded) (optional)</param>
        /// <param name="idShort">The Submodel’s idShort (optional)</param>
        /// <returns>Task of List&lt;Submodel&gt;</returns>
        System.Threading.Tasks.Task<List<Submodel>> GetAllSubmodelsAsync (string semanticId = null, string idShort = null);

        /// <summary>
        /// Returns all Submodels
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="semanticId">The value of the semantic id reference (BASE64-URL-encoded) (optional)</param>
        /// <param name="idShort">The Submodel’s idShort (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;Submodel&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Submodel>>> GetAllSubmodelsAsyncWithHttpInfo (string semanticId = null, string idShort = null);
        /// <summary>
        /// Returns a specific Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of Submodel</returns>
        System.Threading.Tasks.Task<Submodel> GetSubmodelByIdAsync (string submodelIdentifier);

        /// <summary>
        /// Returns a specific Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse (Submodel)</returns>
        System.Threading.Tasks.Task<ApiResponse<Submodel>> GetSubmodelByIdAsyncWithHttpInfo (string submodelIdentifier);
        /// <summary>
        /// Creates a new Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <returns>Task of Submodel</returns>
        System.Threading.Tasks.Task<Submodel> PostSubmodelAsync (Submodel body);

        /// <summary>
        /// Creates a new Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <returns>Task of ApiResponse (Submodel)</returns>
        System.Threading.Tasks.Task<ApiResponse<Submodel>> PostSubmodelAsyncWithHttpInfo (Submodel body);
        /// <summary>
        /// Creates a new or updates an existing Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of Submodel</returns>
        System.Threading.Tasks.Task<Submodel> PutSubmodelByIdAsync (Submodel body, string submodelIdentifier);

        /// <summary>
        /// Creates a new or updates an existing Submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse (Submodel)</returns>
        System.Threading.Tasks.Task<ApiResponse<Submodel>> PutSubmodelByIdAsyncWithHttpInfo (Submodel body, string submodelIdentifier);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class SubmodelRepositoryInterfaceApi : ISubmodelRepositoryInterfaceApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SubmodelRepositoryInterfaceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SubmodelRepositoryInterfaceApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubmodelRepositoryInterfaceApi"/> class
        /// </summary>
        /// <returns></returns>
        public SubmodelRepositoryInterfaceApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubmodelRepositoryInterfaceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SubmodelRepositoryInterfaceApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Deletes a Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns></returns>
        public void DeleteSubmodelById (string submodelIdentifier)
        {
             DeleteSubmodelByIdWithHttpInfo(submodelIdentifier);
        }

        /// <summary>
        /// Deletes a Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteSubmodelByIdWithHttpInfo (string submodelIdentifier)
        {
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRepositoryInterfaceApi->DeleteSubmodelById");

            var localVarPath = "/submodels/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteSubmodelById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Deletes a Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteSubmodelByIdAsync (string submodelIdentifier)
        {
             await DeleteSubmodelByIdAsyncWithHttpInfo(submodelIdentifier);

        }

        /// <summary>
        /// Deletes a Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteSubmodelByIdAsyncWithHttpInfo (string submodelIdentifier)
        {
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRepositoryInterfaceApi->DeleteSubmodelById");

            var localVarPath = "/submodels/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteSubmodelById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Returns all Submodels 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="semanticId">The value of the semantic id reference (BASE64-URL-encoded) (optional)</param>
        /// <param name="idShort">The Submodel’s idShort (optional)</param>
        /// <returns>List&lt;Submodel&gt;</returns>
        public List<Submodel> GetAllSubmodels (string semanticId = null, string idShort = null)
        {
             ApiResponse<List<Submodel>> localVarResponse = GetAllSubmodelsWithHttpInfo(semanticId, idShort);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns all Submodels 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="semanticId">The value of the semantic id reference (BASE64-URL-encoded) (optional)</param>
        /// <param name="idShort">The Submodel’s idShort (optional)</param>
        /// <returns>ApiResponse of List&lt;Submodel&gt;</returns>
        public ApiResponse< List<Submodel> > GetAllSubmodelsWithHttpInfo (string semanticId = null, string idShort = null)
        {

            var localVarPath = "/submodels";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (semanticId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "semanticId", semanticId)); // query parameter
            if (idShort != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "idShort", idShort)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllSubmodels", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Submodel>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Submodel>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Submodel>)));
        }

        /// <summary>
        /// Returns all Submodels 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="semanticId">The value of the semantic id reference (BASE64-URL-encoded) (optional)</param>
        /// <param name="idShort">The Submodel’s idShort (optional)</param>
        /// <returns>Task of List&lt;Submodel&gt;</returns>
        public async System.Threading.Tasks.Task<List<Submodel>> GetAllSubmodelsAsync (string semanticId = null, string idShort = null)
        {
             ApiResponse<List<Submodel>> localVarResponse = await GetAllSubmodelsAsyncWithHttpInfo(semanticId, idShort);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns all Submodels 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="semanticId">The value of the semantic id reference (BASE64-URL-encoded) (optional)</param>
        /// <param name="idShort">The Submodel’s idShort (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;Submodel&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Submodel>>> GetAllSubmodelsAsyncWithHttpInfo (string semanticId = null, string idShort = null)
        {

            var localVarPath = "/submodels";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (semanticId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "semanticId", semanticId)); // query parameter
            if (idShort != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "idShort", idShort)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllSubmodels", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Submodel>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Submodel>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Submodel>)));
        }

        /// <summary>
        /// Returns a specific Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Submodel</returns>
        public Submodel GetSubmodelById (string submodelIdentifier)
        {
             ApiResponse<Submodel> localVarResponse = GetSubmodelByIdWithHttpInfo(submodelIdentifier);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a specific Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Submodel</returns>
        public ApiResponse< Submodel > GetSubmodelByIdWithHttpInfo (string submodelIdentifier)
        {
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRepositoryInterfaceApi->GetSubmodelById");

            var localVarPath = "/submodels/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSubmodelById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Submodel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Submodel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Submodel)));
        }

        /// <summary>
        /// Returns a specific Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of Submodel</returns>
        public async System.Threading.Tasks.Task<Submodel> GetSubmodelByIdAsync (string submodelIdentifier)
        {
             ApiResponse<Submodel> localVarResponse = await GetSubmodelByIdAsyncWithHttpInfo(submodelIdentifier);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns a specific Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse (Submodel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Submodel>> GetSubmodelByIdAsyncWithHttpInfo (string submodelIdentifier)
        {
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRepositoryInterfaceApi->GetSubmodelById");

            var localVarPath = "/submodels/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSubmodelById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Submodel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Submodel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Submodel)));
        }

        /// <summary>
        /// Creates a new Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <returns>Submodel</returns>
        public Submodel PostSubmodel (Submodel body)
        {
             ApiResponse<Submodel> localVarResponse = PostSubmodelWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a new Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <returns>ApiResponse of Submodel</returns>
        public ApiResponse< Submodel > PostSubmodelWithHttpInfo (Submodel body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SubmodelRepositoryInterfaceApi->PostSubmodel");

            var localVarPath = "/submodels";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostSubmodel", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Submodel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Submodel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Submodel)));
        }

        /// <summary>
        /// Creates a new Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <returns>Task of Submodel</returns>
        public async System.Threading.Tasks.Task<Submodel> PostSubmodelAsync (Submodel body)
        {
             ApiResponse<Submodel> localVarResponse = await PostSubmodelAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates a new Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <returns>Task of ApiResponse (Submodel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Submodel>> PostSubmodelAsyncWithHttpInfo (Submodel body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SubmodelRepositoryInterfaceApi->PostSubmodel");

            var localVarPath = "/submodels";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostSubmodel", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Submodel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Submodel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Submodel)));
        }

        /// <summary>
        /// Creates a new or updates an existing Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Submodel</returns>
        public Submodel PutSubmodelById (Submodel body, string submodelIdentifier)
        {
             ApiResponse<Submodel> localVarResponse = PutSubmodelByIdWithHttpInfo(body, submodelIdentifier);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a new or updates an existing Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Submodel</returns>
        public ApiResponse< Submodel > PutSubmodelByIdWithHttpInfo (Submodel body, string submodelIdentifier)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SubmodelRepositoryInterfaceApi->PutSubmodelById");
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRepositoryInterfaceApi->PutSubmodelById");

            var localVarPath = "/submodels/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutSubmodelById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Submodel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Submodel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Submodel)));
        }

        /// <summary>
        /// Creates a new or updates an existing Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of Submodel</returns>
        public async System.Threading.Tasks.Task<Submodel> PutSubmodelByIdAsync (Submodel body, string submodelIdentifier)
        {
             ApiResponse<Submodel> localVarResponse = await PutSubmodelByIdAsyncWithHttpInfo(body, submodelIdentifier);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates a new or updates an existing Submodel 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse (Submodel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Submodel>> PutSubmodelByIdAsyncWithHttpInfo (Submodel body, string submodelIdentifier)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SubmodelRepositoryInterfaceApi->PutSubmodelById");
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRepositoryInterfaceApi->PutSubmodelById");

            var localVarPath = "/submodels/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutSubmodelById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Submodel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Submodel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Submodel)));
        }

    }
}
