/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using AAS.OpenApi.Client.Client;
using AAS.OpenApi.Client.Model;

namespace AAS.OpenApi.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IAssetAdministrationShellBasicDiscoveryApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Deletes all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns></returns>
        void DeleteAllAssetLinksById (string aasIdentifier);

        /// <summary>
        /// Deletes all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteAllAssetLinksByIdWithHttpInfo (string aasIdentifier);
        /// <summary>
        /// Returns a list of Asset Administration Shell ids based on Asset identifier key-value-pairs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetIds">The key-value-pair of an Asset identifier (optional)</param>
        /// <returns>List&lt;string&gt;</returns>
        List<string> GetAllAssetAdministrationShellIdsByAssetLink (List<IdentifierKeyValuePair> assetIds = null);

        /// <summary>
        /// Returns a list of Asset Administration Shell ids based on Asset identifier key-value-pairs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetIds">The key-value-pair of an Asset identifier (optional)</param>
        /// <returns>ApiResponse of List&lt;string&gt;</returns>
        ApiResponse<List<string>> GetAllAssetAdministrationShellIdsByAssetLinkWithHttpInfo (List<IdentifierKeyValuePair> assetIds = null);
        /// <summary>
        /// Returns a list of Asset identifier key-value-pairs based on an Asset Administration Shell id to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>List&lt;IdentifierKeyValuePair&gt;</returns>
        List<IdentifierKeyValuePair> GetAllAssetLinksById (string aasIdentifier);

        /// <summary>
        /// Returns a list of Asset identifier key-value-pairs based on an Asset Administration Shell id to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of List&lt;IdentifierKeyValuePair&gt;</returns>
        ApiResponse<List<IdentifierKeyValuePair>> GetAllAssetLinksByIdWithHttpInfo (string aasIdentifier);
        /// <summary>
        /// Creates all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Asset identifier key-value-pairs</param>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>List&lt;IdentifierKeyValuePair&gt;</returns>
        List<IdentifierKeyValuePair> PostAllAssetLinksById (List<IdentifierKeyValuePair> body, string aasIdentifier);

        /// <summary>
        /// Creates all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Asset identifier key-value-pairs</param>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of List&lt;IdentifierKeyValuePair&gt;</returns>
        ApiResponse<List<IdentifierKeyValuePair>> PostAllAssetLinksByIdWithHttpInfo (List<IdentifierKeyValuePair> body, string aasIdentifier);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Deletes all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteAllAssetLinksByIdAsync (string aasIdentifier);

        /// <summary>
        /// Deletes all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteAllAssetLinksByIdAsyncWithHttpInfo (string aasIdentifier);
        /// <summary>
        /// Returns a list of Asset Administration Shell ids based on Asset identifier key-value-pairs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetIds">The key-value-pair of an Asset identifier (optional)</param>
        /// <returns>Task of List&lt;string&gt;</returns>
        System.Threading.Tasks.Task<List<string>> GetAllAssetAdministrationShellIdsByAssetLinkAsync (List<IdentifierKeyValuePair> assetIds = null);

        /// <summary>
        /// Returns a list of Asset Administration Shell ids based on Asset identifier key-value-pairs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetIds">The key-value-pair of an Asset identifier (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;string&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<string>>> GetAllAssetAdministrationShellIdsByAssetLinkAsyncWithHttpInfo (List<IdentifierKeyValuePair> assetIds = null);
        /// <summary>
        /// Returns a list of Asset identifier key-value-pairs based on an Asset Administration Shell id to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of List&lt;IdentifierKeyValuePair&gt;</returns>
        System.Threading.Tasks.Task<List<IdentifierKeyValuePair>> GetAllAssetLinksByIdAsync (string aasIdentifier);

        /// <summary>
        /// Returns a list of Asset identifier key-value-pairs based on an Asset Administration Shell id to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse (List&lt;IdentifierKeyValuePair&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<IdentifierKeyValuePair>>> GetAllAssetLinksByIdAsyncWithHttpInfo (string aasIdentifier);
        /// <summary>
        /// Creates all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Asset identifier key-value-pairs</param>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of List&lt;IdentifierKeyValuePair&gt;</returns>
        System.Threading.Tasks.Task<List<IdentifierKeyValuePair>> PostAllAssetLinksByIdAsync (List<IdentifierKeyValuePair> body, string aasIdentifier);

        /// <summary>
        /// Creates all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Asset identifier key-value-pairs</param>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse (List&lt;IdentifierKeyValuePair&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<IdentifierKeyValuePair>>> PostAllAssetLinksByIdAsyncWithHttpInfo (List<IdentifierKeyValuePair> body, string aasIdentifier);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class AssetAdministrationShellBasicDiscoveryApi : IAssetAdministrationShellBasicDiscoveryApi
    {
        private AAS.OpenApi.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetAdministrationShellBasicDiscoveryApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AssetAdministrationShellBasicDiscoveryApi(String basePath)
        {
            this.Configuration = new AAS.OpenApi.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = AAS.OpenApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetAdministrationShellBasicDiscoveryApi"/> class
        /// </summary>
        /// <returns></returns>
        public AssetAdministrationShellBasicDiscoveryApi()
        {
            this.Configuration = AAS.OpenApi.Client.Client.Configuration.Default;

            ExceptionFactory = AAS.OpenApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetAdministrationShellBasicDiscoveryApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AssetAdministrationShellBasicDiscoveryApi(AAS.OpenApi.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = AAS.OpenApi.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = AAS.OpenApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AAS.OpenApi.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AAS.OpenApi.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Deletes all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns></returns>
        public void DeleteAllAssetLinksById (string aasIdentifier)
        {
             DeleteAllAssetLinksByIdWithHttpInfo(aasIdentifier);
        }

        /// <summary>
        /// Deletes all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteAllAssetLinksByIdWithHttpInfo (string aasIdentifier)
        {
            // verify the required parameter 'aasIdentifier' is set
            if (aasIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'aasIdentifier' when calling AssetAdministrationShellBasicDiscoveryApi->DeleteAllAssetLinksById");

            var localVarPath = "./lookup/shells/{aasIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aasIdentifier != null) localVarPathParams.Add("aasIdentifier", this.Configuration.ApiClient.ParameterToString(aasIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteAllAssetLinksById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Deletes all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteAllAssetLinksByIdAsync (string aasIdentifier)
        {
             await DeleteAllAssetLinksByIdAsyncWithHttpInfo(aasIdentifier);

        }

        /// <summary>
        /// Deletes all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteAllAssetLinksByIdAsyncWithHttpInfo (string aasIdentifier)
        {
            // verify the required parameter 'aasIdentifier' is set
            if (aasIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'aasIdentifier' when calling AssetAdministrationShellBasicDiscoveryApi->DeleteAllAssetLinksById");

            var localVarPath = "./lookup/shells/{aasIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aasIdentifier != null) localVarPathParams.Add("aasIdentifier", this.Configuration.ApiClient.ParameterToString(aasIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteAllAssetLinksById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Returns a list of Asset Administration Shell ids based on Asset identifier key-value-pairs 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetIds">The key-value-pair of an Asset identifier (optional)</param>
        /// <returns>List&lt;string&gt;</returns>
        public List<string> GetAllAssetAdministrationShellIdsByAssetLink (List<IdentifierKeyValuePair> assetIds = null)
        {
             ApiResponse<List<string>> localVarResponse = GetAllAssetAdministrationShellIdsByAssetLinkWithHttpInfo(assetIds);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a list of Asset Administration Shell ids based on Asset identifier key-value-pairs 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetIds">The key-value-pair of an Asset identifier (optional)</param>
        /// <returns>ApiResponse of List&lt;string&gt;</returns>
        public ApiResponse< List<string> > GetAllAssetAdministrationShellIdsByAssetLinkWithHttpInfo (List<IdentifierKeyValuePair> assetIds = null)
        {

            var localVarPath = "./lookup/shells";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (assetIds != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "assetIds", assetIds)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllAssetAdministrationShellIdsByAssetLink", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<string>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (List<string>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<string>)));
        }

        /// <summary>
        /// Returns a list of Asset Administration Shell ids based on Asset identifier key-value-pairs 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetIds">The key-value-pair of an Asset identifier (optional)</param>
        /// <returns>Task of List&lt;string&gt;</returns>
        public async System.Threading.Tasks.Task<List<string>> GetAllAssetAdministrationShellIdsByAssetLinkAsync (List<IdentifierKeyValuePair> assetIds = null)
        {
             ApiResponse<List<string>> localVarResponse = await GetAllAssetAdministrationShellIdsByAssetLinkAsyncWithHttpInfo(assetIds);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns a list of Asset Administration Shell ids based on Asset identifier key-value-pairs 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetIds">The key-value-pair of an Asset identifier (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;string&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<string>>> GetAllAssetAdministrationShellIdsByAssetLinkAsyncWithHttpInfo (List<IdentifierKeyValuePair> assetIds = null)
        {

            var localVarPath = "./lookup/shells";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (assetIds != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "assetIds", assetIds)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllAssetAdministrationShellIdsByAssetLink", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<string>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (List<string>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<string>)));
        }

        /// <summary>
        /// Returns a list of Asset identifier key-value-pairs based on an Asset Administration Shell id to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>List&lt;IdentifierKeyValuePair&gt;</returns>
        public List<IdentifierKeyValuePair> GetAllAssetLinksById (string aasIdentifier)
        {
             ApiResponse<List<IdentifierKeyValuePair>> localVarResponse = GetAllAssetLinksByIdWithHttpInfo(aasIdentifier);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a list of Asset identifier key-value-pairs based on an Asset Administration Shell id to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of List&lt;IdentifierKeyValuePair&gt;</returns>
        public ApiResponse< List<IdentifierKeyValuePair> > GetAllAssetLinksByIdWithHttpInfo (string aasIdentifier)
        {
            // verify the required parameter 'aasIdentifier' is set
            if (aasIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'aasIdentifier' when calling AssetAdministrationShellBasicDiscoveryApi->GetAllAssetLinksById");

            var localVarPath = "./lookup/shells/{aasIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aasIdentifier != null) localVarPathParams.Add("aasIdentifier", this.Configuration.ApiClient.ParameterToString(aasIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllAssetLinksById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<IdentifierKeyValuePair>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (List<IdentifierKeyValuePair>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<IdentifierKeyValuePair>)));
        }

        /// <summary>
        /// Returns a list of Asset identifier key-value-pairs based on an Asset Administration Shell id to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of List&lt;IdentifierKeyValuePair&gt;</returns>
        public async System.Threading.Tasks.Task<List<IdentifierKeyValuePair>> GetAllAssetLinksByIdAsync (string aasIdentifier)
        {
             ApiResponse<List<IdentifierKeyValuePair>> localVarResponse = await GetAllAssetLinksByIdAsyncWithHttpInfo(aasIdentifier);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns a list of Asset identifier key-value-pairs based on an Asset Administration Shell id to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse (List&lt;IdentifierKeyValuePair&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<IdentifierKeyValuePair>>> GetAllAssetLinksByIdAsyncWithHttpInfo (string aasIdentifier)
        {
            // verify the required parameter 'aasIdentifier' is set
            if (aasIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'aasIdentifier' when calling AssetAdministrationShellBasicDiscoveryApi->GetAllAssetLinksById");

            var localVarPath = "./lookup/shells/{aasIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aasIdentifier != null) localVarPathParams.Add("aasIdentifier", this.Configuration.ApiClient.ParameterToString(aasIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllAssetLinksById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<IdentifierKeyValuePair>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (List<IdentifierKeyValuePair>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<IdentifierKeyValuePair>)));
        }

        /// <summary>
        /// Creates all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Asset identifier key-value-pairs</param>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>List&lt;IdentifierKeyValuePair&gt;</returns>
        public List<IdentifierKeyValuePair> PostAllAssetLinksById (List<IdentifierKeyValuePair> body, string aasIdentifier)
        {
             ApiResponse<List<IdentifierKeyValuePair>> localVarResponse = PostAllAssetLinksByIdWithHttpInfo(body, aasIdentifier);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Asset identifier key-value-pairs</param>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of List&lt;IdentifierKeyValuePair&gt;</returns>
        public ApiResponse< List<IdentifierKeyValuePair> > PostAllAssetLinksByIdWithHttpInfo (List<IdentifierKeyValuePair> body, string aasIdentifier)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling AssetAdministrationShellBasicDiscoveryApi->PostAllAssetLinksById");
            // verify the required parameter 'aasIdentifier' is set
            if (aasIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'aasIdentifier' when calling AssetAdministrationShellBasicDiscoveryApi->PostAllAssetLinksById");

            var localVarPath = "./lookup/shells/{aasIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aasIdentifier != null) localVarPathParams.Add("aasIdentifier", this.Configuration.ApiClient.ParameterToString(aasIdentifier)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostAllAssetLinksById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<IdentifierKeyValuePair>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (List<IdentifierKeyValuePair>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<IdentifierKeyValuePair>)));
        }

        /// <summary>
        /// Creates all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Asset identifier key-value-pairs</param>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of List&lt;IdentifierKeyValuePair&gt;</returns>
        public async System.Threading.Tasks.Task<List<IdentifierKeyValuePair>> PostAllAssetLinksByIdAsync (List<IdentifierKeyValuePair> body, string aasIdentifier)
        {
             ApiResponse<List<IdentifierKeyValuePair>> localVarResponse = await PostAllAssetLinksByIdAsyncWithHttpInfo(body, aasIdentifier);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Asset identifier key-value-pairs</param>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse (List&lt;IdentifierKeyValuePair&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<IdentifierKeyValuePair>>> PostAllAssetLinksByIdAsyncWithHttpInfo (List<IdentifierKeyValuePair> body, string aasIdentifier)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling AssetAdministrationShellBasicDiscoveryApi->PostAllAssetLinksById");
            // verify the required parameter 'aasIdentifier' is set
            if (aasIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'aasIdentifier' when calling AssetAdministrationShellBasicDiscoveryApi->PostAllAssetLinksById");

            var localVarPath = "./lookup/shells/{aasIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (aasIdentifier != null) localVarPathParams.Add("aasIdentifier", this.Configuration.ApiClient.ParameterToString(aasIdentifier)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostAllAssetLinksById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<IdentifierKeyValuePair>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (List<IdentifierKeyValuePair>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<IdentifierKeyValuePair>)));
        }

    }
}
