/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using AAS.OpenApi.Client.Client;
using AAS.OpenApi.Client.Model;

namespace AAS.OpenApi.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IDescriptorInterfaceApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Returns the self-describing information of a network resource (Descriptor)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Descriptor&gt;</returns>
        List<Descriptor> GetDescriptor ();

        /// <summary>
        /// Returns the self-describing information of a network resource (Descriptor)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Descriptor&gt;</returns>
        ApiResponse<List<Descriptor>> GetDescriptorWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Returns the self-describing information of a network resource (Descriptor)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;Descriptor&gt;</returns>
        System.Threading.Tasks.Task<List<Descriptor>> GetDescriptorAsync ();

        /// <summary>
        /// Returns the self-describing information of a network resource (Descriptor)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;Descriptor&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Descriptor>>> GetDescriptorAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class DescriptorInterfaceApi : IDescriptorInterfaceApi
    {
        private AAS.OpenApi.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptorInterfaceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DescriptorInterfaceApi(String basePath)
        {
            this.Configuration = new AAS.OpenApi.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = AAS.OpenApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptorInterfaceApi"/> class
        /// </summary>
        /// <returns></returns>
        public DescriptorInterfaceApi()
        {
            this.Configuration = AAS.OpenApi.Client.Client.Configuration.Default;

            ExceptionFactory = AAS.OpenApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptorInterfaceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DescriptorInterfaceApi(AAS.OpenApi.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = AAS.OpenApi.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = AAS.OpenApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AAS.OpenApi.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AAS.OpenApi.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Returns the self-describing information of a network resource (Descriptor) 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Descriptor&gt;</returns>
        public List<Descriptor> GetDescriptor ()
        {
             ApiResponse<List<Descriptor>> localVarResponse = GetDescriptorWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the self-describing information of a network resource (Descriptor) 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Descriptor&gt;</returns>
        public ApiResponse< List<Descriptor> > GetDescriptorWithHttpInfo ()
        {

            var localVarPath = "/descriptor";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDescriptor", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Descriptor>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Descriptor>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Descriptor>)));
        }

        /// <summary>
        /// Returns the self-describing information of a network resource (Descriptor) 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;Descriptor&gt;</returns>
        public async System.Threading.Tasks.Task<List<Descriptor>> GetDescriptorAsync ()
        {
             ApiResponse<List<Descriptor>> localVarResponse = await GetDescriptorAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns the self-describing information of a network resource (Descriptor) 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;Descriptor&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Descriptor>>> GetDescriptorAsyncWithHttpInfo ()
        {

            var localVarPath = "/descriptor";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDescriptor", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Descriptor>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Descriptor>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Descriptor>)));
        }

    }
}
