/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using AAS.OpenApi.Client.Client;
using AAS.OpenApi.Client.Model;

namespace AAS.OpenApi.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ISubmodelRegistryInterfaceApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Deletes a Submodel Descriptor, i.e. de-registers a submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns></returns>
        void DeleteSubmodelDescriptorById (string submodelIdentifier);

        /// <summary>
        /// Deletes a Submodel Descriptor, i.e. de-registers a submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteSubmodelDescriptorByIdWithHttpInfo (string submodelIdentifier);
        /// <summary>
        /// Returns all Submodel Descriptors
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;SubmodelDescriptor&gt;</returns>
        List<SubmodelDescriptor> GetAllSubmodelDescriptors ();

        /// <summary>
        /// Returns all Submodel Descriptors
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;SubmodelDescriptor&gt;</returns>
        ApiResponse<List<SubmodelDescriptor>> GetAllSubmodelDescriptorsWithHttpInfo ();
        /// <summary>
        /// Returns a specific Submodel Descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>SubmodelDescriptor</returns>
        SubmodelDescriptor GetSubmodelDescriptorById (string submodelIdentifier);

        /// <summary>
        /// Returns a specific Submodel Descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of SubmodelDescriptor</returns>
        ApiResponse<SubmodelDescriptor> GetSubmodelDescriptorByIdWithHttpInfo (string submodelIdentifier);
        /// <summary>
        /// Creates a new Submodel Descriptor, i.e. registers a submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <returns>SubmodelDescriptor</returns>
        SubmodelDescriptor PostSubmodelDescriptor (SubmodelDescriptor body);

        /// <summary>
        /// Creates a new Submodel Descriptor, i.e. registers a submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <returns>ApiResponse of SubmodelDescriptor</returns>
        ApiResponse<SubmodelDescriptor> PostSubmodelDescriptorWithHttpInfo (SubmodelDescriptor body);
        /// <summary>
        /// Updates an existing Submodel Descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns></returns>
        void PutSubmodelDescriptorById (SubmodelDescriptor body, string submodelIdentifier);

        /// <summary>
        /// Updates an existing Submodel Descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PutSubmodelDescriptorByIdWithHttpInfo (SubmodelDescriptor body, string submodelIdentifier);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Deletes a Submodel Descriptor, i.e. de-registers a submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteSubmodelDescriptorByIdAsync (string submodelIdentifier);

        /// <summary>
        /// Deletes a Submodel Descriptor, i.e. de-registers a submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteSubmodelDescriptorByIdAsyncWithHttpInfo (string submodelIdentifier);
        /// <summary>
        /// Returns all Submodel Descriptors
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;SubmodelDescriptor&gt;</returns>
        System.Threading.Tasks.Task<List<SubmodelDescriptor>> GetAllSubmodelDescriptorsAsync ();

        /// <summary>
        /// Returns all Submodel Descriptors
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;SubmodelDescriptor&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<SubmodelDescriptor>>> GetAllSubmodelDescriptorsAsyncWithHttpInfo ();
        /// <summary>
        /// Returns a specific Submodel Descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of SubmodelDescriptor</returns>
        System.Threading.Tasks.Task<SubmodelDescriptor> GetSubmodelDescriptorByIdAsync (string submodelIdentifier);

        /// <summary>
        /// Returns a specific Submodel Descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse (SubmodelDescriptor)</returns>
        System.Threading.Tasks.Task<ApiResponse<SubmodelDescriptor>> GetSubmodelDescriptorByIdAsyncWithHttpInfo (string submodelIdentifier);
        /// <summary>
        /// Creates a new Submodel Descriptor, i.e. registers a submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <returns>Task of SubmodelDescriptor</returns>
        System.Threading.Tasks.Task<SubmodelDescriptor> PostSubmodelDescriptorAsync (SubmodelDescriptor body);

        /// <summary>
        /// Creates a new Submodel Descriptor, i.e. registers a submodel
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <returns>Task of ApiResponse (SubmodelDescriptor)</returns>
        System.Threading.Tasks.Task<ApiResponse<SubmodelDescriptor>> PostSubmodelDescriptorAsyncWithHttpInfo (SubmodelDescriptor body);
        /// <summary>
        /// Updates an existing Submodel Descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PutSubmodelDescriptorByIdAsync (SubmodelDescriptor body, string submodelIdentifier);

        /// <summary>
        /// Updates an existing Submodel Descriptor
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PutSubmodelDescriptorByIdAsyncWithHttpInfo (SubmodelDescriptor body, string submodelIdentifier);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class SubmodelRegistryInterfaceApi : ISubmodelRegistryInterfaceApi
    {
        private AAS.OpenApi.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SubmodelRegistryInterfaceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SubmodelRegistryInterfaceApi(String basePath)
        {
            this.Configuration = new AAS.OpenApi.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = AAS.OpenApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubmodelRegistryInterfaceApi"/> class
        /// </summary>
        /// <returns></returns>
        public SubmodelRegistryInterfaceApi()
        {
            this.Configuration = AAS.OpenApi.Client.Client.Configuration.Default;

            ExceptionFactory = AAS.OpenApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubmodelRegistryInterfaceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SubmodelRegistryInterfaceApi(AAS.OpenApi.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = AAS.OpenApi.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = AAS.OpenApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AAS.OpenApi.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AAS.OpenApi.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Deletes a Submodel Descriptor, i.e. de-registers a submodel 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns></returns>
        public void DeleteSubmodelDescriptorById (string submodelIdentifier)
        {
             DeleteSubmodelDescriptorByIdWithHttpInfo(submodelIdentifier);
        }

        /// <summary>
        /// Deletes a Submodel Descriptor, i.e. de-registers a submodel 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteSubmodelDescriptorByIdWithHttpInfo (string submodelIdentifier)
        {
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRegistryInterfaceApi->DeleteSubmodelDescriptorById");

            var localVarPath = "./registry/submodel-descriptors/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteSubmodelDescriptorById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Deletes a Submodel Descriptor, i.e. de-registers a submodel 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteSubmodelDescriptorByIdAsync (string submodelIdentifier)
        {
             await DeleteSubmodelDescriptorByIdAsyncWithHttpInfo(submodelIdentifier);

        }

        /// <summary>
        /// Deletes a Submodel Descriptor, i.e. de-registers a submodel 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteSubmodelDescriptorByIdAsyncWithHttpInfo (string submodelIdentifier)
        {
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRegistryInterfaceApi->DeleteSubmodelDescriptorById");

            var localVarPath = "./registry/submodel-descriptors/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteSubmodelDescriptorById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Returns all Submodel Descriptors 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;SubmodelDescriptor&gt;</returns>
        public List<SubmodelDescriptor> GetAllSubmodelDescriptors ()
        {
             ApiResponse<List<SubmodelDescriptor>> localVarResponse = GetAllSubmodelDescriptorsWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns all Submodel Descriptors 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;SubmodelDescriptor&gt;</returns>
        public ApiResponse< List<SubmodelDescriptor> > GetAllSubmodelDescriptorsWithHttpInfo ()
        {

            var localVarPath = "./registry/submodel-descriptors";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllSubmodelDescriptors", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<SubmodelDescriptor>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (List<SubmodelDescriptor>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<SubmodelDescriptor>)));
        }

        /// <summary>
        /// Returns all Submodel Descriptors 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;SubmodelDescriptor&gt;</returns>
        public async System.Threading.Tasks.Task<List<SubmodelDescriptor>> GetAllSubmodelDescriptorsAsync ()
        {
             ApiResponse<List<SubmodelDescriptor>> localVarResponse = await GetAllSubmodelDescriptorsAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns all Submodel Descriptors 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;SubmodelDescriptor&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<SubmodelDescriptor>>> GetAllSubmodelDescriptorsAsyncWithHttpInfo ()
        {

            var localVarPath = "./registry/submodel-descriptors";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllSubmodelDescriptors", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<SubmodelDescriptor>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (List<SubmodelDescriptor>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<SubmodelDescriptor>)));
        }

        /// <summary>
        /// Returns a specific Submodel Descriptor 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>SubmodelDescriptor</returns>
        public SubmodelDescriptor GetSubmodelDescriptorById (string submodelIdentifier)
        {
             ApiResponse<SubmodelDescriptor> localVarResponse = GetSubmodelDescriptorByIdWithHttpInfo(submodelIdentifier);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns a specific Submodel Descriptor 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of SubmodelDescriptor</returns>
        public ApiResponse< SubmodelDescriptor > GetSubmodelDescriptorByIdWithHttpInfo (string submodelIdentifier)
        {
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRegistryInterfaceApi->GetSubmodelDescriptorById");

            var localVarPath = "./registry/submodel-descriptors/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSubmodelDescriptorById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SubmodelDescriptor>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (SubmodelDescriptor) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SubmodelDescriptor)));
        }

        /// <summary>
        /// Returns a specific Submodel Descriptor 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of SubmodelDescriptor</returns>
        public async System.Threading.Tasks.Task<SubmodelDescriptor> GetSubmodelDescriptorByIdAsync (string submodelIdentifier)
        {
             ApiResponse<SubmodelDescriptor> localVarResponse = await GetSubmodelDescriptorByIdAsyncWithHttpInfo(submodelIdentifier);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns a specific Submodel Descriptor 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse (SubmodelDescriptor)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SubmodelDescriptor>> GetSubmodelDescriptorByIdAsyncWithHttpInfo (string submodelIdentifier)
        {
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRegistryInterfaceApi->GetSubmodelDescriptorById");

            var localVarPath = "./registry/submodel-descriptors/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSubmodelDescriptorById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SubmodelDescriptor>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (SubmodelDescriptor) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SubmodelDescriptor)));
        }

        /// <summary>
        /// Creates a new Submodel Descriptor, i.e. registers a submodel 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <returns>SubmodelDescriptor</returns>
        public SubmodelDescriptor PostSubmodelDescriptor (SubmodelDescriptor body)
        {
             ApiResponse<SubmodelDescriptor> localVarResponse = PostSubmodelDescriptorWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a new Submodel Descriptor, i.e. registers a submodel 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <returns>ApiResponse of SubmodelDescriptor</returns>
        public ApiResponse< SubmodelDescriptor > PostSubmodelDescriptorWithHttpInfo (SubmodelDescriptor body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SubmodelRegistryInterfaceApi->PostSubmodelDescriptor");

            var localVarPath = "./registry/submodel-descriptors";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostSubmodelDescriptor", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SubmodelDescriptor>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (SubmodelDescriptor) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SubmodelDescriptor)));
        }

        /// <summary>
        /// Creates a new Submodel Descriptor, i.e. registers a submodel 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <returns>Task of SubmodelDescriptor</returns>
        public async System.Threading.Tasks.Task<SubmodelDescriptor> PostSubmodelDescriptorAsync (SubmodelDescriptor body)
        {
             ApiResponse<SubmodelDescriptor> localVarResponse = await PostSubmodelDescriptorAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates a new Submodel Descriptor, i.e. registers a submodel 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <returns>Task of ApiResponse (SubmodelDescriptor)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SubmodelDescriptor>> PostSubmodelDescriptorAsyncWithHttpInfo (SubmodelDescriptor body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SubmodelRegistryInterfaceApi->PostSubmodelDescriptor");

            var localVarPath = "./registry/submodel-descriptors";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostSubmodelDescriptor", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SubmodelDescriptor>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (SubmodelDescriptor) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SubmodelDescriptor)));
        }

        /// <summary>
        /// Updates an existing Submodel Descriptor 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns></returns>
        public void PutSubmodelDescriptorById (SubmodelDescriptor body, string submodelIdentifier)
        {
             PutSubmodelDescriptorByIdWithHttpInfo(body, submodelIdentifier);
        }

        /// <summary>
        /// Updates an existing Submodel Descriptor 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> PutSubmodelDescriptorByIdWithHttpInfo (SubmodelDescriptor body, string submodelIdentifier)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SubmodelRegistryInterfaceApi->PutSubmodelDescriptorById");
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRegistryInterfaceApi->PutSubmodelDescriptorById");

            var localVarPath = "./registry/submodel-descriptors/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutSubmodelDescriptorById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Updates an existing Submodel Descriptor 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PutSubmodelDescriptorByIdAsync (SubmodelDescriptor body, string submodelIdentifier)
        {
             await PutSubmodelDescriptorByIdAsyncWithHttpInfo(body, submodelIdentifier);

        }

        /// <summary>
        /// Updates an existing Submodel Descriptor 
        /// </summary>
        /// <exception cref="AAS.OpenApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Submodel Descriptor object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> PutSubmodelDescriptorByIdAsyncWithHttpInfo (SubmodelDescriptor body, string submodelIdentifier)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SubmodelRegistryInterfaceApi->PutSubmodelDescriptorById");
            // verify the required parameter 'submodelIdentifier' is set
            if (submodelIdentifier == null)
                throw new ApiException(400, "Missing required parameter 'submodelIdentifier' when calling SubmodelRegistryInterfaceApi->PutSubmodelDescriptorById");

            var localVarPath = "./registry/submodel-descriptors/{submodelIdentifier}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (submodelIdentifier != null) localVarPathParams.Add("submodelIdentifier", this.Configuration.ApiClient.ParameterToString(submodelIdentifier)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutSubmodelDescriptorById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                null);
        }

    }
}
