/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AssetAdministrationShellSerializationInterfaceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AssetAdministrationShellSerializationInterfaceApiTests
    {
        private AssetAdministrationShellSerializationInterfaceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AssetAdministrationShellSerializationInterfaceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssetAdministrationShellSerializationInterfaceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AssetAdministrationShellSerializationInterfaceApi
            //Assert.IsInstanceOfType(typeof(AssetAdministrationShellSerializationInterfaceApi), instance, "instance is a AssetAdministrationShellSerializationInterfaceApi");
        }

        /// <summary>
        /// Test GenerateSerializationByIds
        /// </summary>
        [Test]
        public void GenerateSerializationByIdsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> aasIds = null;
            //List<string> submodelIds = null;
            //bool? includeConceptDescriptions = null;
            //var response = instance.GenerateSerializationByIds(aasIds, submodelIds, includeConceptDescriptions);
            //Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
    }

}
