/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConceptDescriptionRepositoryInterfaceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ConceptDescriptionRepositoryInterfaceApiTests
    {
        private ConceptDescriptionRepositoryInterfaceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ConceptDescriptionRepositoryInterfaceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConceptDescriptionRepositoryInterfaceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ConceptDescriptionRepositoryInterfaceApi
            //Assert.IsInstanceOfType(typeof(ConceptDescriptionRepositoryInterfaceApi), instance, "instance is a ConceptDescriptionRepositoryInterfaceApi");
        }

        /// <summary>
        /// Test DeleteConceptDescriptionById
        /// </summary>
        [Test]
        public void DeleteConceptDescriptionByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string cdIdentifier = null;
            //instance.DeleteConceptDescriptionById(cdIdentifier);
            
        }
        /// <summary>
        /// Test GetAllConceptDescriptions
        /// </summary>
        [Test]
        public void GetAllConceptDescriptionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string idShort = null;
            //string isCaseOf = null;
            //string dataSpecificationRef = null;
            //var response = instance.GetAllConceptDescriptions(idShort, isCaseOf, dataSpecificationRef);
            //Assert.IsInstanceOf<List<ConceptDescription>> (response, "response is List<ConceptDescription>");
        }
        /// <summary>
        /// Test GetConceptDescriptionById
        /// </summary>
        [Test]
        public void GetConceptDescriptionByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string cdIdentifier = null;
            //var response = instance.GetConceptDescriptionById(cdIdentifier);
            //Assert.IsInstanceOf<ConceptDescription> (response, "response is ConceptDescription");
        }
        /// <summary>
        /// Test PostConceptDescription
        /// </summary>
        [Test]
        public void PostConceptDescriptionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConceptDescription body = null;
            //var response = instance.PostConceptDescription(body);
            //Assert.IsInstanceOf<ConceptDescription> (response, "response is ConceptDescription");
        }
        /// <summary>
        /// Test PutConceptDescriptionById
        /// </summary>
        [Test]
        public void PutConceptDescriptionByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConceptDescription body = null;
            //string cdIdentifier = null;
            //instance.PutConceptDescriptionById(body, cdIdentifier);
            
        }
    }

}
