/*
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using AAS.OpenApi.Server.Attributes;

using Microsoft.AspNetCore.Authorization;
using AAS.OpenApi.Server.Models;

namespace AAS.OpenApi.Server.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DescriptorInterfaceApiController : ControllerBase, IDescriptorInterfaceApiController
    { 
        /// <summary>
        /// Returns the self-describing information of a network resource (Descriptor)
        /// </summary>
        /// <response code="200">Requested Descriptor</response>
        [HttpGet]
        [Route("/descriptor")]
        [ValidateModelState]
        [SwaggerOperation("GetDescriptor")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Descriptor>), description: "Requested Descriptor")]
        public virtual IActionResult GetDescriptor()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Descriptor>));
            string exampleJson = null;
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<Descriptor>>(exampleJson)
                        : default(List<Descriptor>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
