/*
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using AAS.OpenApi.Server.Models;

namespace AAS.OpenApi.Server.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface IAASXFileServerInterfaceApiController
    { 
        /// <summary>
        /// Deletes a specific AASX package from the server
        /// </summary>
        
        /// <param name="packageId">The Package Id (BASE64-URL-encoded)</param>
        /// <response code="204">Deleted successfully</response>
        IActionResult DeleteAASXByPackageId([FromRoute][Required]string packageId);

        /// <summary>
        /// Returns a specific AASX package from the server
        /// </summary>
        
        /// <param name="packageId">The package Id (BASE64-URL-encoded)</param>
        /// <response code="200">Requested AASX package</response>
        IActionResult GetAASXByPackageId([FromRoute][Required]string packageId);

        /// <summary>
        /// Returns a list of available AASX packages at the server
        /// </summary>
        
        /// <param name="aasId">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <response code="200">Requested package list</response>
        IActionResult GetAllAASXPackageIds([FromQuery]string aasId);


    }
}
