/*
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using AAS.OpenApi.Server.Models;

namespace AAS.OpenApi.Server.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface IAssetAdministrationShellRepositoryInterfaceApiController
    { 
        /// <summary>
        /// Deletes an Asset Administration Shell
        /// </summary>
        
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <response code="204">Asset Administration Shell deleted successfully</response>
        IActionResult DeleteAssetAdministrationShellById([FromRoute][Required]string aasIdentifier);

        /// <summary>
        /// Returns all Asset Administration Shells
        /// </summary>
        
        /// <param name="assetIds">The key-value-pair of an Asset identifier</param>
        /// <param name="idShort">The Asset Administration Shell’s IdShort</param>
        /// <response code="200">Requested Asset Administration Shells</response>
        IActionResult GetAllAssetAdministrationShells([FromQuery]List<IdentifierKeyValuePair> assetIds, [FromQuery]string idShort);

        /// <summary>
        /// Returns a specific Asset Administration Shell
        /// </summary>
        
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <response code="200">Requested Asset Administration Shell</response>
        IActionResult GetAssetAdministrationShellById([FromRoute][Required]string aasIdentifier);

        /// <summary>
        /// Creates a new Asset Administration Shell
        /// </summary>
        
        /// <param name="body">Asset Administration Shell object</param>
        /// <response code="201">Asset Administration Shell created successfully</response>
        IActionResult PostAssetAdministrationShell([FromBody]AssetAdministrationShell body);

        /// <summary>
        /// Updates an existing Asset Administration Shell
        /// </summary>
        
        /// <param name="body">Asset Administration Shell object</param>
        /// <param name="aasIdentifier">The Asset Administration Shell’s unique id (BASE64-URL-encoded)</param>
        /// <response code="204">Asset Administration Shell updated successfully</response>
        IActionResult PutAssetAdministrationShellById([FromBody]AssetAdministrationShell body, [FromRoute][Required]string aasIdentifier);
    }
}
