/*
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using AAS.OpenApi.Server.Models;

namespace AAS.OpenApi.Server.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface IConceptDescriptionRepositoryInterfaceApiController
    { 
        /// <summary>
        /// Deletes a Concept Description
        /// </summary>
        
        /// <param name="cdIdentifier">The Concept Description’s unique id (BASE64-URL-encoded)</param>
        /// <response code="204">Concept Description deleted successfully</response>
        IActionResult DeleteConceptDescriptionById([FromRoute][Required]string cdIdentifier);

        /// <summary>
        /// Returns all Concept Descriptions
        /// </summary>
        
        /// <param name="idShort">The Concept Description’s IdShort</param>
        /// <param name="isCaseOf">IsCaseOf reference (BASE64-URL-encoded)</param>
        /// <param name="dataSpecificationRef">DataSpecification reference (BASE64-URL-encoded)</param>
        /// <response code="200">Requested Concept Descriptions</response>
        IActionResult GetAllConceptDescriptions([FromQuery]string idShort, [FromQuery]string isCaseOf, [FromQuery]string dataSpecificationRef);

        /// <summary>
        /// Returns a specific Concept Description
        /// </summary>
        
        /// <param name="cdIdentifier">The Concept Description’s unique id (BASE64-URL-encoded)</param>
        /// <response code="200">Requested Concept Description</response>
        IActionResult GetConceptDescriptionById([FromRoute][Required]string cdIdentifier);

        /// <summary>
        /// Creates a new Concept Description
        /// </summary>
        
        /// <param name="body">Concept Description object</param>
        /// <response code="201">Concept Description created successfully</response>
        IActionResult PostConceptDescription([FromBody]ConceptDescription body);

        /// <summary>
        /// Updates an existing Concept Description
        /// </summary>
        
        /// <param name="body">Concept Description object</param>
        /// <param name="cdIdentifier">The Concept Description’s unique id (BASE64-URL-encoded)</param>
        /// <response code="204">Concept Description updated successfully</response>
        IActionResult PutConceptDescriptionById([FromBody]ConceptDescription body, [FromRoute][Required]string cdIdentifier);
    }
}
