/*
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using AAS.OpenApi.Server.Models;

namespace AAS.OpenApi.Server.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface ISubmodelRegistryInterfaceApiController
    { 
        /// <summary>
        /// Deletes a Submodel Descriptor, i.e. de-registers a submodel
        /// </summary>
        
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <response code="204">Submodel Descriptor deleted successfully</response>
        IActionResult DeleteSubmodelDescriptorById([FromRoute][Required]string submodelIdentifier);

        /// <summary>
        /// Returns all Submodel Descriptors
        /// </summary>
        
        /// <response code="200">Requested Submodel Descriptors</response>
        IActionResult GetAllSubmodelDescriptors();

        /// <summary>
        /// Returns a specific Submodel Descriptor
        /// </summary>
        
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <response code="200">Requested Submodel Descriptor</response>
        IActionResult GetSubmodelDescriptorById([FromRoute][Required]string submodelIdentifier);

        /// <summary>
        /// Creates a new Submodel Descriptor, i.e. registers a submodel
        /// </summary>
        
        /// <param name="body">Submodel Descriptor object</param>
        /// <response code="201">Submodel Descriptor created successfully</response>
        IActionResult PostSubmodelDescriptor([FromBody]SubmodelDescriptor body);

        /// <summary>
        /// Updates an existing Submodel Descriptor
        /// </summary>
        
        /// <param name="body">Submodel Descriptor object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <response code="204">Submodel Descriptor updated successfully</response>
        IActionResult PutSubmodelDescriptorById([FromBody]SubmodelDescriptor body, [FromRoute][Required]string submodelIdentifier);
    }
}
