/*
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using AAS.OpenApi.Server.Models;

namespace AAS.OpenApi.Server.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface ISubmodelRepositoryInterfaceApiController
    { 
        /// <summary>
        /// Deletes a Submodel
        /// </summary>
        
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <response code="204">Submodel deleted successfully</response>
        IActionResult DeleteSubmodelById([FromRoute][Required]string submodelIdentifier);

        /// <summary>
        /// Returns all Submodels
        /// </summary>
        
        /// <param name="semanticId">The value of the semantic id reference (BASE64-URL-encoded)</param>
        /// <param name="idShort">The Submodel’s idShort</param>
        /// <response code="200">Requested Submodels</response>
        IActionResult GetAllSubmodels([FromQuery]string semanticId, [FromQuery]string idShort);

        /// <summary>
        /// Returns a specific Submodel
        /// </summary>
        
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <response code="200">Requested Submodel</response>
        IActionResult GetSubmodelById([FromRoute][Required]string submodelIdentifier);

        /// <summary>
        /// Creates a new Submodel
        /// </summary>
        
        /// <param name="body">Submodel object</param>
        /// <response code="201">Submodel created successfully</response>
        IActionResult PostSubmodel([FromBody]Submodel body);

        /// <summary>
        /// Creates a new or updates an existing Submodel
        /// </summary>
        
        /// <param name="body">Submodel object</param>
        /// <param name="submodelIdentifier">The Submodel’s unique id (BASE64-URL-encoded)</param>
        /// <response code="201">Submodel created successfully</response>
        /// <response code="204">Submodel updated successfully</response>
        IActionResult PutSubmodelById([FromBody]Submodel body, [FromRoute][Required]string submodelIdentifier);
    }
}
