/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AssetAdministrationShellDescriptor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssetAdministrationShellDescriptorTests
    {
        // TODO uncomment below to declare an instance variable for AssetAdministrationShellDescriptor
        //private AssetAdministrationShellDescriptor instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssetAdministrationShellDescriptor
            //instance = new AssetAdministrationShellDescriptor();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssetAdministrationShellDescriptor
        /// </summary>
        [Test]
        public void AssetAdministrationShellDescriptorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetAdministrationShellDescriptor
            //Assert.IsInstanceOfType<AssetAdministrationShellDescriptor> (instance, "variable 'instance' is a AssetAdministrationShellDescriptor");
        }


        /// <summary>
        /// Test the property 'Administration'
        /// </summary>
        [Test]
        public void AdministrationTest()
        {
            // TODO unit test for the property 'Administration'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'GlobalAssetId'
        /// </summary>
        [Test]
        public void GlobalAssetIdTest()
        {
            // TODO unit test for the property 'GlobalAssetId'
        }
        /// <summary>
        /// Test the property 'IdShort'
        /// </summary>
        [Test]
        public void IdShortTest()
        {
            // TODO unit test for the property 'IdShort'
        }
        /// <summary>
        /// Test the property 'Identification'
        /// </summary>
        [Test]
        public void IdentificationTest()
        {
            // TODO unit test for the property 'Identification'
        }
        /// <summary>
        /// Test the property 'SpecificAssetIds'
        /// </summary>
        [Test]
        public void SpecificAssetIdsTest()
        {
            // TODO unit test for the property 'SpecificAssetIds'
        }
        /// <summary>
        /// Test the property 'SubmodelDescriptors'
        /// </summary>
        [Test]
        public void SubmodelDescriptorsTest()
        {
            // TODO unit test for the property 'SubmodelDescriptors'
        }

    }

}
