/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Endpoint
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EndpointTests
    {
        // TODO uncomment below to declare an instance variable for Endpoint
        //private Endpoint instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Endpoint
            //instance = new Endpoint();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Endpoint
        /// </summary>
        [Test]
        public void EndpointInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Endpoint
            //Assert.IsInstanceOfType<Endpoint> (instance, "variable 'instance' is a Endpoint");
        }


        /// <summary>
        /// Test the property '_Interface'
        /// </summary>
        [Test]
        public void _InterfaceTest()
        {
            // TODO unit test for the property '_Interface'
        }
        /// <summary>
        /// Test the property 'ProtocolInformation'
        /// </summary>
        [Test]
        public void ProtocolInformationTest()
        {
            // TODO unit test for the property 'ProtocolInformation'
        }

    }

}
