/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PackageDescription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PackageDescriptionTests
    {
        // TODO uncomment below to declare an instance variable for PackageDescription
        //private PackageDescription instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PackageDescription
            //instance = new PackageDescription();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PackageDescription
        /// </summary>
        [Test]
        public void PackageDescriptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PackageDescription
            //Assert.IsInstanceOfType<PackageDescription> (instance, "variable 'instance' is a PackageDescription");
        }


        /// <summary>
        /// Test the property 'AasIds'
        /// </summary>
        [Test]
        public void AasIdsTest()
        {
            // TODO unit test for the property 'AasIds'
        }
        /// <summary>
        /// Test the property 'PackageId'
        /// </summary>
        [Test]
        public void PackageIdTest()
        {
            // TODO unit test for the property 'PackageId'
        }

    }

}
