/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PackagesPackageIdBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PackagesPackageIdBodyTests
    {
        // TODO uncomment below to declare an instance variable for PackagesPackageIdBody
        //private PackagesPackageIdBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PackagesPackageIdBody
            //instance = new PackagesPackageIdBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PackagesPackageIdBody
        /// </summary>
        [Test]
        public void PackagesPackageIdBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PackagesPackageIdBody
            //Assert.IsInstanceOfType<PackagesPackageIdBody> (instance, "variable 'instance' is a PackagesPackageIdBody");
        }


        /// <summary>
        /// Test the property 'AasIds'
        /// </summary>
        [Test]
        public void AasIdsTest()
        {
            // TODO unit test for the property 'AasIds'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Test]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }

    }

}
