/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProtocolInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProtocolInformationTests
    {
        // TODO uncomment below to declare an instance variable for ProtocolInformation
        //private ProtocolInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProtocolInformation
            //instance = new ProtocolInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProtocolInformation
        /// </summary>
        [Test]
        public void ProtocolInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProtocolInformation
            //Assert.IsInstanceOfType<ProtocolInformation> (instance, "variable 'instance' is a ProtocolInformation");
        }


        /// <summary>
        /// Test the property 'EndpointAddress'
        /// </summary>
        [Test]
        public void EndpointAddressTest()
        {
            // TODO unit test for the property 'EndpointAddress'
        }
        /// <summary>
        /// Test the property 'EndpointProtocol'
        /// </summary>
        [Test]
        public void EndpointProtocolTest()
        {
            // TODO unit test for the property 'EndpointProtocol'
        }
        /// <summary>
        /// Test the property 'EndpointProtocolVersion'
        /// </summary>
        [Test]
        public void EndpointProtocolVersionTest()
        {
            // TODO unit test for the property 'EndpointProtocolVersion'
        }
        /// <summary>
        /// Test the property 'Subprotocol'
        /// </summary>
        [Test]
        public void SubprotocolTest()
        {
            // TODO unit test for the property 'Subprotocol'
        }
        /// <summary>
        /// Test the property 'SubprotocolBody'
        /// </summary>
        [Test]
        public void SubprotocolBodyTest()
        {
            // TODO unit test for the property 'SubprotocolBody'
        }
        /// <summary>
        /// Test the property 'SubprotocolBodyEncoding'
        /// </summary>
        [Test]
        public void SubprotocolBodyEncodingTest()
        {
            // TODO unit test for the property 'SubprotocolBodyEncoding'
        }

    }

}
