/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubmodelElementAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmodelElementAttributesTests
    {
        // TODO uncomment below to declare an instance variable for SubmodelElementAttributes
        //private SubmodelElementAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmodelElementAttributes
            //instance = new SubmodelElementAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmodelElementAttributes
        /// </summary>
        [Test]
        public void SubmodelElementAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmodelElementAttributes
            //Assert.IsInstanceOfType<SubmodelElementAttributes> (instance, "variable 'instance' is a SubmodelElementAttributes");
        }


        /// <summary>
        /// Test the property 'EmbeddedDataSpecifications'
        /// </summary>
        [Test]
        public void EmbeddedDataSpecificationsTest()
        {
            // TODO unit test for the property 'EmbeddedDataSpecifications'
        }
        /// <summary>
        /// Test the property 'SemanticId'
        /// </summary>
        [Test]
        public void SemanticIdTest()
        {
            // TODO unit test for the property 'SemanticId'
        }
        /// <summary>
        /// Test the property 'Qualifiers'
        /// </summary>
        [Test]
        public void QualifiersTest()
        {
            // TODO unit test for the property 'Qualifiers'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }

    }

}
